server:
  port: 7070
spring:
  datasource:
    url: jdbc:h2:file:~/h2_test_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
     console:
        enabled: true
        path: /h2
        settings.trace: false
        settings.web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
    change-log: 'classpath:/db/changelog/changelog.xml'
    clear-checksums: false
  aop:
    auto: true

springdoc:
  api-docs:
    path: /api-docs


app:
  scheduling:
    period: 15000
    enabled: false
    priceModificator: 1.1