server:
  port: '7070'
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/Shop_db'
    username: postgres
    password: SQL13
# Alternative configuration of caffeine
#  cache:
#    cache-names: exchangeRates
#    caffeine:
#      spec: maximumSize=5, expireAfterWrite=30s

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: 'classpath:/db/changelog/changelog.xml'
    clear-checksums: true
springdoc:
  api-docs:
    path: /api-docs

app:
  scheduling:
    period: 15000  #15sec scheduler freq. period
    enabled: false
    priceModificator: 1.1
  exchange:
    URL: "http://localhost:7071/exchangerate"
    remoteEnabled: true
logging:
    file.name: DemoShop.log
    level:
      org.springframework.web: DEBUG
      ru.ncs.DemoShop: DEBUG