server:
  servlet:
    context-path: /
  port: ${SERV_PORT:7070}

management:
  health:
    redis:
      enabled: false

  server:
    port: 9090
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,prometheus

spring:
  datasource:
    url: jdbc:h2:file:~/h2_test_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
     console:
        enabled: true
        path: /h2
        settings.trace: false
        settings.web-allow-others: false

  kafka:
    consumer:
      properties:
        spring:
          json:
            value:
              default:
                type: ru.ncs.DemoShop.interaction.ExchangeRate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
    change-log: 'classpath:/db/changelog/changelog.xml'
    clear-checksums: false
  aop:
    auto: true

springdoc:
  api-docs:
    path: /api-docs

app:
  healthCheckMsg: ${HEALTH_MSG:OK}
  scheduling:
    period: 15000  #15sec scheduler freq. period
    enabled: false
    priceModificator: 1.1
  exchange:
    URL: "http://exchangeservice.default.svc.cluster.local:8071/exchangerate"
    remoteEnabled: true

logging:
  file.name: DemoShop.log
  level:
    org.springframework.web: DEBUG
    ru.ncs.DemoShop: DEBUG

appl:
  groupId: groupExch1