server:
  port: '7070'
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/Shop_db'
    username: postgres
    password: SQL13
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: 'classpath:/db/changelog/changelog.xml'
    clear-checksums: false
springdoc:
  api-docs:
    path: /api-docs

app:
  scheduling:
    period: 15000  #15sec scheduler freq. period
    enabled: false
    priceModificator: 1.1