apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoshop-deployment
  labels:
    app: demoshop-app
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: demoshop-app
  template:
    metadata:
      labels:
        app: demoshop-app
    spec:
      containers:
        - name: demoshop
          image: inkgrey/demoshop
          ports:
            - containerPort: 8000
              name: app
            - containerPort: 9090
              name: actuator
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
          livenessProbe:
            httpGet:
              port: 9090
              path: /health
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8000
              path: /healthcheck
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              port: 8000
              path: /healthcheck
            failureThreshold: 30
            periodSeconds: 10